### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by Protuhj** [jgallagher/lostark-refinement#1]
Can you add a dark mode toggle?

**Comment by jgallagher** [comment]
Good idea; will see what I can do.

**Comment by Bonzai2022** [comment]
This would be nice. It's much to bright.

**Comment by jgallagher** [comment]
There is now a light/dark selector at the top:

<img width="385" alt="Screen Shot 2022-02-20 at 1 59 30 PM" src="https://user-images.githubusercontent.com/1435635/154859464-ba461a56-517e-4bf5-8836-7c56a88c831d.png">

You may have to force-reload to refresh.

**Comment by Protuhj** [comment]
This looks so good, thank you!
