### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by cpiscos** [jgallagher/lostark-refinement#2]
I was wondering if there was any plan to release the source code. I’m interested in learning the game theory and solver mechanics.

Thanks

**Comment by jgallagher** [comment]
Yes, I've been meaning to release it but haven't gotten around to it yet. FWIW the solver is not particularly smart; it builds a brute force map of the optimal solution for every possible state, and then directs you to that choice as you progress through refinement.

**Comment by ahxnxa** [comment]
+1 on source, we could do some nice things with it. Lovely work by the way!

**Comment by jgallagher** [comment]
Source code is now published, although note that this is _very_ much a rough, in-my-free-time kind of thing, and my response time will be usually be measured in days.

The interesting bits for solving are where the map of all states to their best solution is built: https://github.com/jgallagher/lostark-refinement/blob/main/src/app/solution.rs#L122-L176. Once that's built, we can [look up](https://github.com/jgallagher/lostark-refinement/blob/main/src/app/solution.rs#L179-L181) the optimal solution for any current [game state](https://github.com/jgallagher/lostark-refinement/blob/main/src/app/solution.rs#L13-L17).
